
cellInfo = { ...
{...
'Motor_Info_in_Bus',...
'',...
sprintf('exceptional input signal'), ...
'Auto',...
'-1', {...
{'dummy', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'dummy signal' };...
 } ...
 } ...
{...
'Motor_in_Bus',...
'',...
sprintf('physical input signal'), ...
'Auto',...
'-1', {...
{'BattVolt', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'V', 'battery voltage' };...
{'MotorSpd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rad/s', 'motor speed' };...
 } ...
 } ...
{...
'Motor_Info_out_Bus',...
'',...
sprintf('information signal'), ...
'Auto',...
'-1', {...
{'MechPwr', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'W', 'motor output power' };...
{'PwrLoss', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'W', 'motor loss power' };...
 } ...
 } ...
{...
'Motor_sensor_Bus',...
'',...
sprintf('senor signal'), ...
'Auto',...
'-1', {...
{'Motor_power', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'W', 'motor output power' };...
 } ...
 } ...
{...
'Motor_out_Bus',...
'',...
sprintf(''), ...
'Auto',...
'-1', {...
{'MotorAmp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'A', 'motor current' };...
{'MotorTrq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', 'motor torque' };...
 } ...
 } ...
 }';
 Simulink.Bus.cellToObject(cellInfo);
 clear cellInfo 
