
cellInfo = { ...
{...
'MotorCtrl_Bus',...
'',...
sprintf('モーター制御信号バス'), ...
'Auto',...
'-1', {...
{'MtrCtrl_MotorTrqDem', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', 'モーター要求トルク' };...
 } ...
 } ...
{...
'MotorCtrl_PwtrCAN_Rx_Bus',...
'',...
sprintf('モーター制御パワートレインCAN受信信号バス'), ...
'Auto',...
'-1', {...
{'TmCtrl_Clutch_position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'モーター供給トルク' };...
{'HEVCtrl_Motor_torque_request', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', 'HEVモーター要求トルク' };...
{'EngCtrl_Engine_speed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rpm', 'エンジン回転速度' };...
 } ...
 } ...
{...
'MotorCtrl_PwtrCAN_Tx_Bus',...
'',...
sprintf('モーター制御パワートレインCAN送信信号バス'), ...
'Auto',...
'-1', {...
{'MtrCtrl_Motor_torque_actual', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', 'モーター供給トルク' };...
{'MtrCtrl_Motor_torque_available', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', '力行供給可能トルク' };...
{'MtrCtrl_Motor_regen_torque_available', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', '回生供給可能トルク' };...
 } ...
 } ...
{...
'MotorCtrl_Info_Bus',...
'',...
sprintf('モーター制御情報'), ...
'Auto',...
'-1', {...
{'MtrCtrl_MotorSpd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rpm', 'モーター回転速度' };...
 } ...
 } ...
 }';
 Simulink.Bus.cellToObject(cellInfo);
 clear cellInfo 
